main
  pull_request:
name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    executor:
      name: "docker"
      image: "openjdk:11"
      options:
        always:
        - "--shm-size=1g"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          sonar.projectKey: Sambit-rgb_Java-Damn-Vulnerable-Bank
          sonar.organization: sambit-rgb
          sonar.mode: ci
          sonar.sources: .
